security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Baldeweg\Entity\User:
            algorithm: bcrypt
            cost: 15

    providers:
        app_user_provider:
            entity:
                class: Baldeweg\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: app_user_provider
            http_basic: true

    access_decision_manager:
        strategy: unanimous

    access_control: ~
