parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Baldeweg\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Baldeweg\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
