parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Incwadi\Core\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Incwadi\Core\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
